trigger:
  branches:
    include:
      - master
#pr: none
#stages:
#  - template: templates/build.yml
stages:
  - stage: Docker
    displayName: Build & Push Docker image to AWS ECR
    jobs:
      - job: Build_and_Push
        displayName: Build & Push Docker image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              repository: plazoleta

          - task: ECRPushImage@1
            inputs:
              awsCredentials: 'AWS_ECR'
              regionName: us-east-1
              imageSource: 'imagename'
              sourceImageName: plazoleta
              sourceImageTag: latest
              pushTag: latest
              repositoryName: plazoleta