trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: '680989793215'
  IMAGE_NAME: 'plazoleta'
  EB_APPLICATION_NAME: 'plazoleta'
  EB_ENVIRONMENT_NAME: 'Plazoleta-env'

jobs:
  - job: build
    displayName: 'Build and Deploy'
    steps:
      - checkout: self

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - script: |
          ./gradlew build --no-daemon
        displayName: 'Build with Gradle'

      - script: |
          ./gradlew test jacocoTestReport sonar --no-daemon
        displayName: 'Run tests and generate coverage report'

      - task: InstallAwsCli@1
        inputs:
          version: '2'

      - task: AWSCLI@1
        displayName: 'Configure AWS credentials'
        inputs:
          awsCredentials: 'GitHubActionsAwsCredentials'
          awsRegion: '$(AWS_REGION)'

      - task: AWSCLI@1
        displayName: 'Login to AWS ECR'
        inputs:
          awsCredentials: 'GitHubActionsAwsCredentials'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com

      - script: |
          docker build -t $(IMAGE_NAME) .
          docker tag $(IMAGE_NAME) $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(IMAGE_NAME)
        displayName: 'Build and tag Docker image'

      - script: |
          docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(IMAGE_NAME)
        displayName: 'Push Docker image to ECR'

      - script: |
          aws s3 cp Dockerrun.aws.json s3://elasticbeanstalk-us-east-1-$(AWS_ACCOUNT_ID)/$(Build.SourceVersion)-Dockerrun.aws.json
        displayName: 'Upload Dockerrun.aws.json to S3'

      - script: |
          aws elasticbeanstalk create-application-version --application-name $(EB_APPLICATION_NAME) --version-label $(Build.SourceVersion) --source-bundle S3Bucket=elasticbeanstalk-us-east-1-$(AWS_ACCOUNT_ID),S3Key=$(Build.SourceVersion)-Dockerrun.aws.json
          aws elasticbeanstalk update-environment --application-name $(EB_APPLICATION_NAME) --environment-name $(EB_ENVIRONMENT_NAME) --version-label $(Build.SourceVersion)
        displayName: 'Deploy to Elastic Beanstalk'
