name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 680989793215
  IMAGE_NAME: plazoleta

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests and generate coverage report
        run: ./gradlew test jacocoTestReport sonar --no-daemon

#      - name: Login to AWS ECR
#        uses: aws-actions/amazon-ecr-login@v1
#        with:
#          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
#          region: ${{ env.AWS_REGION }}
#
#      - name: Build and tag Docker image
#        run: |
#          docker build -t $IMAGE_NAME .
#          docker tag $IMAGE_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
#
#      - name: Push Docker image to ECR
#        run: |
#          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME
